from typing import Optional
import re
from loguru import logger

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "C# / .NET": [
        r"\bc\s*#",
        r"\b\.net\b",
        r"\bdotnet\b",
        r"\basp\.net\b",
        r"\bvb\.net\b",
        r"\bcsharp\b",
        r"\bblazor\b",
        r"\bentity\s*framework\b",
        r"\bwinforms\b",
        r"\bwpf\b",
        r"\b\.exe\b",
        r"\bси шарп\b",
    ],
    "Design": [
        r"\bдизайн\b",
        r"\bдизайн[аеу]",
        r"\bлоготип\b",
        r"\bлого\b",
        r"\bфирменн[ыо][йг]?\s*стил[ья]\b",
        r"\bбренд\b",
        r"\bbranding\b",
        r"\bfigma\b",
        r"\bфотошоп\b",
        r"\bphotoshop\b",
        r"\billustrator\b",
        r"\bcorel\b",
        r"\bиллюстраци[яй]\b",
        r"\bграфическ[ио][ймх]?\s*дизайн\b",
        r"\bфото\b",
        r"\bпечат\w*\b",
        r"\bхолст\w*\b",
        r"\bдорисовк\w*\b",
        r"\bдизайн[аеу]?\s+интерьер\b",
        r"\bинтерьер\b",
        r"\bмакет\b",
        r"\bprototype\b",
        r"\bпрототип\b",
        r"\bui\s*design\b",
        r"\bux\s*design\b",
        r"\buxui\b",
        r"\bграфическ[ио][йх]?\s*редактор\b",
        r"\bcanva\b",
        r"\bsketch\b.*\bapp\b",
        r"\bдизайн.*мебел\b",
    ],
    "Marketing": [
        r"\bреклам[аы]",
        r"\bмаркетинг\b",
        r"\bmarketing\b",
        r"\bseo\b",
        r"\bпродвижени[ея]\b",
        r"\bрассылк[аи]\b",
        r"\bemail.*рассылк\b",
        r"\bemail.*marketing\b",
        r"\btarget\b",
        r"\bтаргет\b",
        r"\bконтекстн[аяой]+\s*реклам\b",
        r"\bgoogle\s*ads\b",
        r"\bянд[еи]кс\s*директ\b",
        r"\bsmm\b",
        r"\bsmm\s*продвижени\b",
        r"\bпродвижени[ея]\s*в\s*соц\b",
        r"\btraffic\b",
        r"\bтрафик\b",
        r"\bконверси[яй]\b",
        r"\bворонк[аи]\s*продаж\b",
        r"\blead\b",
        r"\bлид[ыо]?\b",
        r"\bгенераци[яй]\s*лид\b",
    ],
    "WordPress": [
        r"\bwordpress\b",
        r"\bwp\b(?!\.)",
        r"\bwoocommerce\b",
        r"\bwoo\b",
        r"\bthemes?\b.*\b(?:wordpress|wp)",
        r"\bplugins?\b.*\b(?:wordpress|wp)",
        r"\belementor\b",
        r"\bdivi\b",
        r"\bacf\b",
        r"\badvanced custom fields\b",
        r"\bвордпресс\b",
        r"\bсайт.*wp\b",
        r"\bсайт.*вордпресс\b",
        r"\bwordpress.*сайт\b",
    ],
    "Tilda": [
        r"\btilda\b",
        r"\btil?d[ae]?\b",
        r"\bтильд[аы]\b",
    ],
    "Shopify": [
        r"\bshopify\b",
        r"\bshopify\s*(?:theme|app|store|development)\b",
        r"\bliquid\b.*\bshopify\b",
        r"\bshopify\s*api\b",
    ],
    "Frontend": [
        r"\bfrontend\b",
        r"\bfront-end\b",
        r"\bфронтенд\b",
        r"\bверстк[ау]?\b",
        r"\bверстальщик\b",
        r"\bhtml\b",
        r"\bcss\b",
        r"\bhtml5?\b",
        r"\bcss3?\b",
        r"\bjavascript\b",
        r"\bjs\b(?!\.)",
        r"\bes6\+\b",
        r"\btypescript\b",
        r"\bangular\b(?:\s+\d)?",
        r"\bvue\b",
        r"\bvue\.?js\b",
        r"\bsvelte\b",
        r"\bwebpack\b",
        r"\bvite\b",
        r"\btailwind\b",
        r"\bbootstrap\b",
        r"\bsass\b",
        r"\bscss\b",
        r"\bless\b",
        r"\bresponsive\b",
        r"\badaptive\b",
        r"\bcross.browser\b",
        r"\brundown\b",
        r"\bbem\b",
        r"\bинтерфейс\b",
        r"\bлендинг",
        r"\blending\s*page\b",
        r"\blp\b(?!\.)",
        r"\bсоздани[ея]\s*сайт\w*",
        r"\bразработк[аи]\s*сайт\w*",
        r"\bдобавлени\w*\s*товар\w*\s*на\s*сайт",
        r"\bтовар\w*\s*на\s*сайт",
    ],
    "React": [
        r"\breact\b",
        r"\breact\.?js\b",
        r"\breactjs\b",
        r"\bredux\b",
        r"\breact\s*native\b",
        r"\bnext\.?js\b",
        r"\bgatsby\b",
        r"\breact\s*hooks?\b",
        r"\brtk\b",
        r"\bquery\b.*\breact\b",
        r"\bреакт\b",
        r"\brdt\b",
    ],
    "Next.js": [
        r"\bnext\.?js\b",
        r"\bnextjs\b",
        r"\bnext\.?\s*\d+\b",
        r"\bapp\s*router\b",
        r"\bpages\s*router\b",
        r"\bssr\b",
        r"\bssg\b",
        r"\bserver\s*components?\b",
    ],
    "Backend": [
        r"\bbackend\b",
        r"\bback-end\b",
        r"\bback\s*end\b",
        r"\bбэкенд\b",
        r"\bсерверн[аяой]+\b",
        r"\bбэкэнд\b",
        r"\bapi\b",
        r"\brest\s*api\b",
        r"\bgraphql\b",
        r"\bgrpc\b",
        r"\bwebsocket\b",
        r"\bwebsockets?\b",
        r"\bmicroservice\b",
        r"\bsoap\b",
        r"\bcrud\b",
        r"\b1с\b",
        r"\b1c\b",
        r"\b1-с\b",
        r"\bпрограмм[аы]?\s*учет[а]?\b",
        r"\bбухгалтер\b",
    ],
    "FastAPI": [
        r"\bfastapi\b",
        r"\bfast\s*api\b",
        r"\buvicorn\b",
        r"\bpydantic\b.*\bfastapi\b",
    ],
    "Django": [
        r"\bdjango\b",
        r"\bdjango\s*rest\b",
        r"\bdrf\b",
        r"\bdjango\s*admin\b",
        r"\bdjango\s*orm\b",
    ],
    "Laravel": [
        r"\blaravel\b",
        r"\blaravel\s*\d+\b",
        r"\bphp\b.*\blaravel\b",
        r"\beloquent\b",
        r"\blivewire\b",
        r"\bfilament\b",
    ],
    "Fullstack": [
        r"\bfullstack\b",
        r"\bfull.stack\b",
        r"\bfull\s*stack\b",
        r"\bmern\b",
        r"\bmean\b",
        r"\bpern\b",
        r"\bфулстек\b",
        r"\bфуллстек\b",
        r"\bфул\s*стек\b",
    ],
    "Telegram Bots": [
        r"\btelegram\s*bot\b",
        r"\btelegram.*\b(?:bot|бот)",
        r"\btg\s*bot\b",
        r"\btelegraf\b",
        r"\baiogram\b",
        r"\bpython-telegram\b",
        r"\bpyrogram\b",
        r"\bbot\s*telegram\b",
        r"\bтелеграм\s*бот\b",
        r"\bтелеграм.*\b(?:бот|бoт)",
        r"\bтг\s*бот\b",
        r"\bбот.*телеграм\b",
        r"\btelegram\s*bot\s*(?:на|для)\b",
        r"\bбот.*tg\b",
        r"\bбот[аоие]?\b",
        r"\bbot\b",
    ],
    "Discord Bots": [
        r"\bdiscord\s*bot\b",
        r"\bdsicord\.?js\b",
        r"\bpy-cord\b",
        r"\bdiscord\.py\b",
        r"\bnextcord\b",
        r"\bhikari\b",
    ],
    "AI Chatbots": [
        r"\bchatbot\b",
        r"\bchat\s*bot\b",
        r"\bai\b",
        r"\bai\s*chatbot\b",
        r"\bconversational\s*ai\b",
        r"\bchatgpt\s*bot\b",
        r"\bdialogflow\b",
        r"\brag\b.*\bchat\b",
        r"\bqa\s*bot\b",
        r"\bknowledge\s*bot\b",
        r"\bvirtual\s*assistant\b",
    ],
    "AI Agents": [
        r"\bai\s*agent\b",
        r"\bautonomous\s*agent\b",
        r"\bllm\s*agent\b",
        r"\bcrewai\b",
        r"\bautogpt\b",
        r"\bbabyagi\b",
        r"\blanggraph\b",
        r"\bmulti-agent\b",
        r"\btool\s*use\b",
    ],
    "RAG": [
        r"\brag\b",
        r"\bretrieval.augmented\b",
        r"\bretrieval\s*augmented\b",
        r"\bvector\s*database\b",
        r"\bvectordb\b",
        r"\bembedding\b",
        r"\bsemantic\s*search\b",
        r"\bhybrid\s*search\b",
        r"\bpinecone\b",
        r"\bweaviate\b",
        r"\bchromadb\b",
        r"\bmilvus\b",
        r"\bqdrant\b",
        r"\bllamaindex\b",
        r"\bllama\s*index\b",
    ],
    "OpenAI Integration": [
        r"\bopenai\b",
        r"\bgpt[-\s]?[345]?\b",
        r"\bgpt4\b",
        r"\bchatgpt\b",
        r"\bgpt.4o\b",
        r"\bwhisper\b",
        r"\bdall.e\b",
        r"\bassistants?\s*api\b",
        r"\bopenai\s*api\b",
        r"\bgpt.3.5\b",
    ],
    "Claude Integration": [
        r"\bclaude\b",
        r"\banthropic\b",
        r"\bclaude\s*api\b",
        r"\bclaude\s*sonnet\b",
        r"\bclaude\s*haiku\b",
        r"\bclaude\s*opus\b",
    ],
    "Web Scraping": [
        r"\bweb\s*scrap(?:ing|er|e)\b",
        r"\bscrap(?:ing|er|e)\b.*\bweb\b",
        r"\bcrawl(?:er|ing)\b",
        r"\bspider\b",
        r"\bhtml\s*pars(?:ing|er)\b",
        r"\bscrapy\b",
        r"\bselenium\b",
        r"\bplaywright\b",
        r"\bbeautifulsoup\b",
        r"\bhttpx\b",
        r"\brecaptcha\b",
        r"\bbypass\s*captcha\b",
        r"\bпарсинг\b",
        r"\bпарс[ие]\b",
        r"\bпарссер\w*",
        r"\bскраппинг\b",
        r"\bсбор\s*данных\b",
        r"\bкраулер\b",
        r"\bкраулинг\b",
    ],
    "Parsing": [
        r"\bpars(?:ing|er|e)\b",
        r"\bdata\s*extract\b",
        r"\bextract\s*data\b",
        r"\bjson\s*pars(?:er|ing)\b",
        r"\bxml\s*pars(?:er|ing)\b",
        r"\bpdf\s*pars(?:ing|er)\b",
        r"\bdoc\s*pars(?:ing|er)\b",
        r"\bcsv\s*pars(?:ing|er)\b",
        r"\blog\s*pars(?:ing|er)\b",
    ],
    "Automation": [
        r"\bautomation\b",
        r"\bautomate\b",
        r"\bworkflow\b",
        r"\bworkflow\s*automation\b",
        r"\bprocess\s*automation\b",
        r"\brpa\b",
        r"\brobotic\b",
        r"\bselenium\b",
        r"\btask\s*schedul(?:ing|er)\b",
        r"\bcron\b",
        r"\bавтоматизаци[яи]\b",
        r"\bавтоматизироват[ьы]\b",
    ],
    "n8n": [
        r"\bn8n\b",
        r"\bn8n\.io\b",
        r"\bn8n\s*workflow\b",
        r"\bn8n\s*nodes?\b",
    ],
    "Make": [
        r"\bmake\.com\b",
        r"\bintegromat\b",
        r"\bmake\s*automation\b",
        r"\bmake\s*scenario\b",
        r"\bmake\.com\s*automation\b",
        r"\b(?:integromat|make\.com)\b",
    ],
    "Zapier": [
        r"\bzapier\b",
        r"\bzap\b",
        r"\bzapier\s*integration\b",
        r"\bzapier\s*zap\b",
    ],
    "Mobile Apps": [
        r"\bmobile\s*app\b",
        r"\bmobile\s*application\b",
        r"\bios\s*app\b",
        r"\bandroid\s*app\b",
        r"\bcross.platform\s*app\b",
        r"\bhybrid\s*app\b",
        r"\bapp\s*development\b",
        r"\bмобильн[оы][ех]?\s*приложени[йе]\b",
        r"\bприложени[ея]\s*(?:под|для)\s*(?:ios|android)\b",
    ],
    "Flutter": [
        r"\bflutter\b",
        r"\bdart\b",
        r"\bflutter\s*app\b",
        r"\bflutter\s*development\b",
        r"\bflutterflow\b",
    ],
    "React Native": [
        r"\breact\s*native\b",
        r"\breactnative\b",
        r"\brn\b(?!\.)",
        r"\bexpo\b",
        r"\bexpo\s*go\b",
    ],
    "Android": [
        r"\bandroid\b",
        r"\bkotlin\b",
        r"\bjava\s*android\b",
        r"\bandroid\s*studio\b",
        r"\bgradle\b",
        r"\bjetpack\s*compose\b",
        r"\bmaterial\s*design\b",
    ],
    "iOS": [
        r"\bios\b",
        r"\bswift\b",
        r"\bswiftui\b",
        r"\buikit\b",
        r"\bapple\s*app\b",
        r"\bipad\s*app\b",
        r"\biphone\s*app\b",
        r"\bxc?code\b",
        r"\bcocoapods?\b",
        r"\bspm\b",
    ],
    "DevOps": [
        r"\bdevops\b",
        r"\bci/cd\b",
        r"\bci\.cd\b",
        r"\bcontinuous\s*integration\b",
        r"\bcontinuous\s*deployment\b",
        r"\bdeployment\b",
        r"\bdeploy\b",
        r"\bgithub\s*actions\b",
        r"\bgitlab\s*ci\b",
        r"\bjenkins\b",
        r"\bansible\b",
        r"\bterraform\b",
        r"\bhelm\b",
        r"\bprometheus\b",
        r"\bgrafana\b",
        r"\bmonitoring\b",
    ],
    "Docker": [
        r"\bdocker\b",
        r"\bdockerfile\b",
        r"\bdocker.compose\b",
        r"\bdocker\s*container\b",
        r"\bcontainerization\b",
        r"\bcontainer\s*orchestrat\b",
        r"\bдокер\b",
    ],
    "Kubernetes": [
        r"\bkubernetes\b",
        r"\bk8s\b",
        r"\bkube\b",
        r"\bminikube\b",
        r"\bistio\b",
        r"\bkubectl\b",
        r"\bopenshift\b",
        r"\baks\b",
        r"\beks\b",
        r"\bgke\b",
        r"\bкубер\b",
    ],
    "QA": [
        r"\bqa\b",
        r"\bquality\s*assurance\b",
        r"\btesting\b",
        r"\btest\s*automation\b",
        r"\bmanual\s*testing\b",
        r"\bregression\s*testing\b",
        r"\bunit\s*test\b",
        r"\bintegration\s*test\b",
        r"\be2e\b",
        r"\bend.to.end\b",
        r"\bcypress\b",
        r"\bplaywright\s*test\b",
        r"\bselenium\b",
        r"\bjest\b",
        r"\bvitest\b",
        r"\bpostman\b",
        r"\bapi\s*test\b",
        r"\bload\s*test\b",
        r"\bperformance\s*test\b",
        r"\bтестировани[ея]\b",
        r"\bтест\s*кейс[ы]?\b",
        r"\bтестов[аы]+\b",
        r"\bтестировщик\b",
        r"\bqa\s*инженер\b",
    ],
    "Data Analytics": [
        r"\bdata\s*analytics\b",
        r"\bdata\s*analysis\b",
        r"\banalytics\b",
        r"\bbusiness\s*intelligence\b",
        r"\bbi\s*analyst\b",
        r"\betl\b",
        r"\bdata\s*pipeline\b",
        r"\bdata\s*engineer\b",
        r"\bdata\s*warehouse\b",
        r"\bdashboard\b",
        r"\bdata\s*viz\b",
        r"\bdata\s*visualization\b",
        r"\btableau\b",
        r"\blooker\b",
        r"\bmetabase\b",
        r"\bredash\b",
        r"\bsuperset\b",
    ],
    "Power BI": [
        r"\bpower\s*bi\b",
        r"\bpowerbi\b",
        r"\bpower\s*bi\s*dashboard\b",
        r"\bdax\b",
        r"\bm\s*language\b",
        r"\bpower\s*query\b",
    ],
    "SQL": [
        r"\bsql\b",
        r"\bpostgresql\b",
        r"\bmysql\b",
        r"\bmariadb\b",
        r"\bsqlite\b",
        r"\boracle\s*sql\b",
        r"\bmssql\b",
        r"\bsql\s*server\b",
        r"\bquery\b",
        r"\bdatabase\s*design\b",
        r"\bcomplex\s*query\b",
        r"\bjoin\b",
        r"\bsubquery\b",
        r"\bindex\b",
        r"\bview\b",
        r"\bstored\s*procedures?\b",
        r"\btrigger\b",
        r"\bnormalization\b",
        r"\bбаз[аы]\s*данных\b",
        r"\bбд\b(?!\.)",
        r"\bpostgres\b",
    ],
    "Machine Learning": [
        r"\bmachine\s*learning\b",
        r"\bml\b",
        r"\bdeep\s*learning\b",
        r"\bнейросет[ьи]\b",
        r"\bнейронн[аяой]+\s*сет[ьи]\b",
        r"\bneural\s*network\b",
        r"\bai\s*model\b",
        r"\btensorflow\b",
        r"\bpytorch\b",
        r"\bkeras\b",
        r"\bxgboost\b",
        r"\blightgbm\b",
        r"\bscikit.learn\b",
        r"\bsklearn\b",
        r"\btrain(?:ing)?\s*model\b",
        r"\bml\s*model\b",
        r"\bnlp\b",
        r"\bnatural\s*language\b",
        r"\brecommendation\s*system\b",
        r"\brecommender\b",
        r"\bclassif(?:ication|ier)\b",
        r"\bregression\b",
        r"\bclustering\b",
        r"\bobject\s*detection\b",
        r"\bimage\s*classif\b",
        r"\btime\s*series\b",
        r"\bfeature\s*engineer\b",
        r"\bfeature\s*extract\b",
    ],
    "Computer Vision": [
        r"\bcomputer\s*vison\b",
        r"\bimage\s*recogni\b",
        r"\bobject\s*detection\b",
        r"\bimage\s*segmentation\b",
        r"\bface\s*recogni\b",
        r"\bocr\b",
        r"\boptical\s*character\b",
        r"\byolo\b",
        r"\bopencv\b",
        r"\bpil\b",
        r"\bimage\s*process\b",
        r"\bvideo\s*analytics\b",
        r"\bimage\s*analytics\b",
        r"\baugmented\s*reality\b",
        r"\bdeep\s*learning\b.*\bimage\b",
    ],
}


def classify_task(title: str, description: Optional[str] = None) -> tuple[str, float]:
    text = (title + " " + (description or "")).lower()

    scores: dict[str, float] = {}
    for category, patterns in CATEGORY_KEYWORDS.items():
        score = 0.0
        for pattern in patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                score += len(matches) * 2.0

                if title and re.search(pattern, title, re.IGNORECASE):
                    score += 3.0

        if score > 0:
            scores[category] = score

    if not scores:
        return "OTHER", 0.0

    best_category = max(scores, key=scores.get)
    best_score = scores[best_category]

    return best_category, best_score


class CategoryNormalizer:
    def __init__(self) -> None:
        self.category_keywords = CATEGORY_KEYWORDS

    def normalize(
        self,
        task_title: str,
        task_description: Optional[str] = None,
        category_raw: Optional[str] = None,
    ) -> str:
        category, score = classify_task(task_title, task_description)

        if category == "OTHER" and category_raw:
            category, score = classify_task(category_raw)

        return category

    def get_subcategory(
        self, title: str, description: Optional[str] = None
    ) -> Optional[str]:
        category, score = classify_task(title, description)
        return category if category != "OTHER" else None


normalizer = CategoryNormalizer()
